export const CONSTANTE = {
  REQUEST_LIST_MAINTENANCE: '@listMaintenance/REQUEST_LIST_MAINTENANCE',
  RESPONSE_LIST_MAINTENANCE: '@listMaintenance/RESPONSE_LIST_MAINTENANCE',
  LOADING_LIST_MAINTENANCE: '@listMaintenance/LOADING_LIST_MAINTENANCE',
};
