export const CONSTANTE = {
  REQUEST_LIST_GASOLINE: '@listGasoline/REQUEST_LIST_GASOLINE',
  RESPONSE_LIST_GASOLINE: '@listGasoline/RESPONSE_LIST_GASOLINE',
  LOADING_LIST_GASOLINE: '@listGasoline/LOADING_LIST_GASOLINE',
};
